# This is a sample GitLab CI/CD configuration file for a Maven project

image: maven:3.6.3-jdk-11

stages:
  - build_and_test
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build_and_test
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/

variables:
  REMOTE_SERVER: "ljthey.co.uk"
  REMOTE_USER: "ice"
  JAR_FILE: "target/IceBreakerBackend-1.0.jar"
  SSH_PASSWORD: "$CI_SSH_PASSWORD"

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y openssh-client
    - apt-get install -y sshpass

    # Copy the JAR file to the remote server
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$JAR_FILE" "$REMOTE_USER@$REMOTE_SERVER:IceBreaker/cicd/"
