# This is a sample GitLab CI/CD configuration file for a Maven project

image: maven:3.8.1-jdk-11

stages:
  - build_and_test
  - deploy

cache:
  paths:
    - .m2/repository

build:
  stage: build_and_test
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/

variables:
  REMOTE_SERVER: "ljthey.co.uk"
  REMOTE_USER: "ice"
  JAR_FILE: "target/IceBreakerBackend-1.0.jar"
  SSH_PASSWORD: "$CI_SSH_PASSWORD"
  EXISTING_PORT: 8080

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y openssh-client
    - apt-get install -y sshpass

    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "pkill -f 'java -jar IceBreakerBackend-1.0.jar'"
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "nohup java -jar IceBreakerBackend-1.0.jar &>/dev/null &"
    - echo $(sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$REMOTE_USER@$REMOTE_SERVER" "lsof -i :$EXISTING_PORT -t || echo 'not_found'")
